### PR TITLE
update the run state before fetching runoutput

### PR DESCRIPTION
**Pull request by storey247**
Fix for #130 

Updating the run instance before calling the `RunsGetOutput` method means that if the call to `RunsGetOutput` fails then the newly created run is updated in K8s correctly and wont have invalid state.

### CODE REVIEW

**Comment by storey247** [comment]
Sorry, there were some rebase conflicts and issues i had to resolve because of the other PR's that had gone in

**Comment by stuartleeks** [comment]
@Azadehkhojandi - I see that you approved this earlier. Are you ok to give this a quick check again now that @storey247 has rebased, and merge if it looks ok?

**Pull request merged**
