### PR TITLE
Rewrite the operator to use go directly to communicate with Databricks

### PR DESCRIPTION
**Pull request by xinsnake**

### CODE REVIEW

**Comment by xtellurian** [comment]
addresses issue #24

**Comment by xinsnake** [comment]
```
go test ./pkg/... ./cmd/... -coverprofile cover.out
?       microsoft/azure-databricks-operator/pkg/apis    [no test files]
?       microsoft/azure-databricks-operator/pkg/apis/microsoft  [no test files]
ok      microsoft/azure-databricks-operator/pkg/apis/microsoft/v1beta1  4.438s  coverage: 23.5% of statements
?       microsoft/azure-databricks-operator/pkg/controller      [no test files]
ok      microsoft/azure-databricks-operator/pkg/controller/notebookjob  26.303s coverage: 62.1% of statements
?       microsoft/azure-databricks-operator/pkg/rand    [no test files]
?       microsoft/azure-databricks-operator/pkg/webhook [no test files]
?       microsoft/azure-databricks-operator/cmd/manager [no test files]
```

**Comment by xinsnake** [comment]
We need to remove the tests from the PR check because the tests are integrating to DataBricks which is not possible to run in a PR securely.

**Comment by xtellurian** [comment]
there are some big changes to the codebase here. We should not PR directly into master. 

Please PR into the branch `feat/pure-go`

**Comment by xtellurian** [comment]
there are some big changes to the codebase here. We should not PR directly into master. 

Please PR into the branch `feat/pure-go`

**Pull request merged**
